### ISSUE TITLE
Duplicated sticker

### ISSUE THREAD

**Issue by rockenbach** [luizcarvalho/stickers#1]
There are two files for the 'xama' sticker:

- [fisrt](https://github.com/luizcarvalho/stickers/blob/master/figurinhas/22aa5b39-6aea-43fd-a68b-ee469a006ee8.webp.png)
- [second](https://github.com/luizcarvalho/stickers/blob/master/figurinhas/8cf5fb82-0016-4562-9cb6-807658c22fdf.jpg.webp.png): this image has a bit more definition and I suggest to keep it

**Comment by luizcarvalho** [comment]
Thanks Brow!!
